# yamllint disable rule:key-ordering
# yamllint disable rule:line-length

name: Check latest release version and update AUR packege
# yamllint disable-line rule:truthy
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 21 * * *

jobs:
  aur_check_update:
    uses: rgeraskin/github-workflows-deploy-aur-on-thirdparty-repo/.github/workflows/aur_check_update.yaml@main
    with:
      aur_username: Roman Geraskin
      updater_release_url: https://api.github.com/repos/werf/werf/releases/latest
      updater_username: GitHub Actions
    secrets:
      aur_email: ${{ secrets.AUR_EMAIL }}
      aur_ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      updater_email: 51863158+rgeraskin@users.noreply.github.com
